pkgs/sops-install-secrets/main.go, pkgs/sops-install-secrets/nixos-test.nix
we should not lookup users there
=> fix user manifest validation in sandbox

README.md
=> Fixing secrets path in README

pkgs/sops-install-secrets/main.go, pkgs/sops-install-secrets/test-assets/secrets.yaml
=> fix sops files that contains lists

modules/sops/default.nix
This is the continuation of #48, but I now understand paths and string contexts a little better.
I have
- made the `validateSopsFiles -> isPath sopsFile` assertion also accept strings that are store paths. This has the side effect that `sopsFile` can now refer to arbitrary derivations, so I had to replace `builtins.toFile` with `pkgs.writeText`.
- changed the type of `sopsFile` and `defaultSopsFile` to just `path` (which already accepts both strings and paths).
- merged the two assertions about `gnupgHome` and `sshKeyPaths` into a single one
- moved the `pathExists sopsFile` assertion into `config.assertions`.
The first point is the one that deserves discussion: what I was failing to understand before is that strings that start with `/nix/store` generally have an associated *context*, …
=> Improve assertions

default.nix, go.mod, go.sum, pkgs/sops-install-secrets/sshkeys/convert.go
=> switch to maintained openpgp library

pkgs/sops-install-secrets/nixos-test.nix
This is needed since https://github.com/NixOS/nixpkgs/pull/133166 is merged
=> Fix pipeline on unstable

README.md
The 2b section is wrongly written as the second 2a. xD
=> [F] Fix typo in README.md, 2a -> 2b.

README.md, modules/sops/default.nix, pkgs/sops-install-secrets/main.go, pkgs/sops-install-secrets/nixos-test.nix
=> Allow setting user passwords

modules/sops/default.nix, pkgs/sops-install-secrets/main.go, pkgs/sops-install-secrets/nixos-test.nix
=> Prune old secrets generations

modules/sops/default.nix
Should hopefully help with #23
=> Support arbitrary environment variables

modules/sops/default.nix, pkgs/sops-install-secrets/nixos-test.nix
Also add a test case for this.
Closes #137
=> Fix user passwords disappearing

modules/sops/default.nix
We are planning to use this in our CI pipeline
=> module: Expose manifests

README.md, modules/sops/default.nix, pkgs/sops-install-secrets/main.go, pkgs/sops-install-secrets/main_test.go, pkgs/sops-install-secrets/nixos-test.nix
We also have service reloads now, so add them as well
=> Re-add service restarts

.github/workflows/test.yml, .gitlab-ci.yml, README.md, flake.lock, flake.nix, unit-tests.nix
Better example to avoid: https://github.com/Mic92/sops-nix/issues/175
=> README: add toString to sopsPGPKeyDirs

pkgs/sops-install-secrets/nixos-test.nix
=> Fix test indentation once and for all

modules/sops/default.nix
Separate out `sops-install-secrets` into a 'runtime version' and 'check version', so that even if the builder cannot run target code it still works.
Works a bit like the sshd module in nixpkgs:
https://github.com/NixOS/nixpkgs/blob/d632b9657c7dd5c994e5cdf0bc71cb016f63efa1/nixos/modules/services/networking/ssh/sshd.nix#L7-L13
=> Add validationPackage option for cross-compilation

modules/sops/default.nix
=> module: add defaultText to validationPackage

flake.lock, pkgs/sops-init-gpg-key/default.nix, pkgs/sops-install-secrets/shell.nix, pkgs/unit-tests.nix, shell.nix
fixes https://github.com/Mic92/sops-nix/issues/232
=>  no longer use out-dated aliases 

flake.nix, modules/home-manager/sops.nix
Been using this branch with gpg for quite a while, cannot promise that it will work with age though as I didn't test it.
=> Flake + fixes for home-manager

README.md
cc @dasJ does helsinki systems also wants to be mentioned here?
=> README: commercial support

README.md, default.nix, flake.nix, modules/home-manager/sops.nix, modules/sops/default.nix, pkgs/sops-install-secrets/darwin.go, pkgs/sops-install-secrets/default.nix, pkgs/sops-install-secrets/linux.go, pkgs/sops-install-secrets/main.go, pkgs/sops-install-secrets/main_test.go
=> Synced feat/home-manager with master

README.md
fixes https://github.com/Mic92/sops-nix/issues/276
bors merge
=> drop warning on tmpfs for XDG_RUNTIME_DIR

flake.nix
this message seems to come up even if you don't use this attribute...
bors merge
=> drop nixosModule warning

pkgs/sops-install-secrets/darwin.go
I discovered a few issues when running nix-sops on macOS Ventura; each commit has some documentation explaining its rationale.
=> fix: darwin setup on ventura

modules/sops/templates/default.nix
https://github.com/NixOS/nixpkgs/commit/834f0d660a79e8f08c108237d76fc1b42024289b
=> modules/sops/templates: isCoercibleToString -> isConvertibleWithToString

pkgs/sops-install-secrets/darwin.go
=> fix: add missing argument for MountSecretFs on darwin

modules/home-manager/sops.nix
Make sure passwords are ready for services part of graphical-session.target
=> fix: systemd unit file

README.md
Based on https://github.com/getsops/sops/issues/594#issuecomment-569132718 and tested locally successful
=> Suggest command to encrypt binary that respect .sopy.aml

README.md
fixes https://github.com/Mic92/sops-nix/issues/445
=> README: link to infra repo instead of my dotfiles

flake.lock, flake.nix, modules/sops/default.nix, modules/sops/manifest-for.nix, modules/sops/secrets-for-users/default.nix, modules/sops/with-environment.nix
This preparation to support sysusers.
No behavior change.
=> move secrets-fo-users to it's own module

modules/home-manager/sops.nix
Correct a bug where 'KeepAlive' in the launchd service 'org.nix-community.home.sops-nix.plist'
re-runs 'sops-nix-user' every few seconds.
This should run:
- once at boot
- once at home-manager profile activation
=> home-manager/darwin: run sops-nix-user _once_ on login or activation

modules/home-manager/sops.nix
Sorry my fault - small oversight ✌🏻
=> home-manager: minor oversight cleanup

README.md
=> home-manager: update location where secrets are symlinked

flake.lock, modules/sops/default.nix, modules/sops/secrets-for-users/default.nix, pkgs/sops-install-secrets/nixos-test.nix
=> Support userborn

modules/home-manager/sops.nix, modules/sops/default.nix, modules/sops/templates/default.nix
Fixes https://github.com/NuschtOS/search/issues/126
=> Add some missing literalExpression

pkgs/sops-install-secrets/main.go
If the activation script is called twice for some reason, we might end up with a file potentially opened up and written twice.
=> make writing templates more atomic

README.md
fixes https://github.com/Mic92/sops-nix/issues/740
=> docs: we need systemd/user for home-manager
