Mic92/sops-nix

pkgs/sops-pgp-hook/hook_test.go

There is no guarantee that keys will be returned in a certain order

sops-pgp-hook: make test robust against file order

---

README.md

README: correct mistake in GPG key decryption explanation

---

pkgs/sops-install-secrets/main.go

To keep the existing state machine logic to ensure symlink... this also checks existing symlinks to make sure they're owner/group are correct.
Fixes #30

sops-install-secrets: symlinkSecret: set uid/gid (with Fchownat)

---

pkgs/sops-pgp-hook/sops-pgp-hook.bash

Keep the original shellHook if it is set, and run it after `sopsPGPHook`

---

.github/workflows/test-flakes.yml
flake.nix
pkgs/sops-install-secrets/nixos-test.nix

The flake build did not work on the latest master, specifically `nix flake show` and `nix build .#unit-tests`. I fixed the issues and added basic checks to the CI build to prevent regressions.
Checks are not configured yet, so `nix flake check -L` does not work.

Fix flake build

---

pkgs/sops-init-gpg-key/default.nix
pkgs/sops-install-secrets/default.nix
pkgs/ssh-to-pgp/default.nix

`stdenv.lib` has been deprecated in favor of using `lib` directly.

pkgs: don't reference deprecated stdenv.lib

---

pkgs/sops-pgp-hook/sops-pgp-hook.bash

Fix sops-pgp-hook erroring in a strict shell

---

modules/sops/default.nix

When using `documentation.nixos.includeAllModules = true;`, I'd
otherwise have to rebuild the manual on each change since I have my
`defaultSopsFile` in a git-repo with all my other configs.

module: Don't set option-value as option-default

---

pkgs/sops-install-secrets/main.go

This does not significantly decrease security while making it a lot more
convinient.  There are also services, where it is not possible to set
the keys group i.e. if a daemon unsets all groups.  Processes still
won't be able to list other secrets if they are not in the secret group.
fixes #86

allow non-key group users to access /run/secrets

---

modules/sops/default.nix

* Since 0d957142b6669dcd138fc3518f69d15432c6dcd5 the manual doesn't
build since `<name>` is interpreted by docbook as (unmatched) XML-tag.
I decided to use `<xref linkend` as this provides proper linking to
the referenced option.
* Also, if the module is included on a machine where `sops` isn't used,
but `documentation.nixos.includeAllModules = true;` is set, the module
wouldn't evaluate because `config.sopsFile` is referenced in a
`default`-tag. This is generally an issue since every change to this
option would trigger a rebuild of the manual anyways.
See also 94fd200305ceb031380381ae91a1ffabe9f06706 for that.
cc @Mic92 @NickCao

modules/sops: fix manual

---

flake.nix

Ran into an issue on my M1 macbook because `aarch64-darwin` wasn't in the supported systems list. This PR adds it, I'm assuming it won't break anything existing.

Add aarch64-darwin to supported systems

---

pkgs/sops-install-secrets/main.go

It makes more sense to import the key when we have one and ignore the
SSH keys instead of only importing the key when we have no SSH keys.
This is because we import all SSH keys by default in the module and
using a key file means the use has to explicitly unset the SSH keys.

Swap order of age ssh keys and the key file

---

README.md

This makes several changes to the README to make reading it clearer, based on pain points I had when trying to set this up for the first time.
- General grammar, capitalization, and punctuation fixes.
- Change the usage example into collapsible sections so the README is
navigable.
- Merge steps 2a/2b and steps 3a/3b into steps 2 and 3, since they share
a lot in common.
- Use age examples for .sops.yaml, instead of just GPG fingerprints.
- Make sure there is only one consistent example throughout the
entirety of the usage example.
- Make the age/GPG/SSH trichotomy less confusing.
- Adds a source for the "GnuPG is not great software" claim.

docs: make README.md clearer

---

README.md
pkgs/sops-install-secrets/nixos-test.nix

The required code in nixpkgs was reverted so we should not advertise a
feature that does not work. We can revert this commit if the feature is
re-merged into 22.05 with the proper version in it.

Remove restart logic from README and test

---

modules/sops/default.nix

Useful for things like `sops.environment.SOPS_GPG_EXEC = pkgs.writeShellScript ...`

Allow paths in sops.environment

---

modules/sops/default.nix

I'd like to be able to override the sops-install-secrets package that is used in the module. I build the NixOS configuration for my Raspberry Pi's on my `x86_64-linux` system with the binfmt wrapper:
```
boot.binfmt.emulatedSystems = [ "aarch64-linux" ];
```
Compiling sops-nix like this is slow, plus it also stalls for some unknown reason. With this PR I found the following workaround:
```
outputs = { self, nixpkgs, sops-nix }: {
nixosConfigurations = {
neon = nixpkgs.lib.nixosSystem {
system = "aarch64-linux";
modules = [
./.
{ config._module.args = { inherit (self) modulesPath; }; }
sops-nix.nixosModules.sops
({ pkgs, crossPkgs, ... }: {
sops.package = crossPkgs.sops-install-secrets.override {
inherit (pkgs) go;
};
})
];
specialArgs = {
crossPkgs = import nixpkgs {
localSystem.system = …
```

Add package option to module

---

README.md

The instructions provided point `ssh-to-age` at a public key, which won't (ever?) be encrypted. This removes the SSH private key decryption mention, to not confuse readers.

README: remove mention of decrypting SSH private key

---

pkgs/sops-install-secrets/main.go

This fails otherwise as the users snippet was not executed and the
user/group does not exist.
Closes #222
cc @slothofanarchy

Fix lookup of users/groups in dry activation

---

README.md
pkgs/sops-init-gpg-key/sops-init-gpg-key

This add the option `--keytype` to `sops-init-gpg-key`. If it is missing, the default behaviour is kept and it generates a RSA GPG key - like before. If it is added like `--keytype Curve25119` (see README commit) it will generate a Curve25119 based key. Everything else works as before.

Adding support for generating a Curve25119 based GPG key with sops-init-gpg-key

---

modules/sops/templates/default.nix
pkgs/sops-install-secrets/nixos-test.nix

The `config` argument in submodule shadows the toplevel `config`, which breaks the default settings.
Also add test for testing default settings.

Fix scope in `sops.templates`

---

modules/home-manager/sops.nix

This is a re-submit of #305.  Author has given permission to re-submit in the named PR. 
See my re-submit as approval of the original PR, as i did literally change nothing.
For integration someone need to set the following in their home config to mimic the same logic as the standalone.
```nix
{
self,
config,
lib,
pkgs,
...
}: let
userName = "myUserName";
hmConfig = config.home-manager.users.${userName};
user = config.users.users.${userName};
in {
home-manager.users.${userName} = {
sops = {
age.keyFile = "${hmConfig.xdg.configHome}/sops/age/keys.txt";
defaultSopsFile = ./secrets.yaml;
defaultSymlinkPath = "/run/user/${toString user.uid}/secrets";
defaultSecretsMountPoint = "/run/user/${toString user.uid}/secrets.d";
secrets = {
aSecret = {path = …
```

HM: make `secretsMountPoint` and `symlinkPath` configurable

---

modules/sops/templates/default.nix

This is mainly for fixing this in my systems:
```
error: option sops.templates has no description
error: option sops.templates.<name>.path has no description
Treating warnings as errors. Set documentation.nixos.options.warningsAreErrors to false to ignore these warnings.
```

templates: Add descriptions and use singleLineStr

---

modules/sops/templates/default.nix

When using `documentation.nixos.includeAllModules = true;` this fails for me with
error: attribute 'users' missing
at /nix/store/30jax2y4q3d1xyf8ha3cwilw3kdz4pn8-source/modules/sops/templates/default.nix:8:11:
7|   secretsForUsers = lib.filterAttrs (_: v: v.neededForUsers) cfg.secrets;
8|   users = config.users.users;
|           ^
9| in {
(use '--show-trace' to show detailed location information)
Not depending on `config` when building the manual fixes the issue.
cc @mic92 @Ninlives

modules/sops/templates: declare `defaultText` for `sops.templates.<name>.group`

---

pkgs/sops-import-keys-hook/default.nix
pkgs/sops-pgp-hook/default.nix

From [nixpkgs](https://github.com/NixOS/nixpkgs/blob/c333779d748a996a9a305b3d1fcf6b12b51564ed/pkgs/build-support/trivial-builders.nix#L598):
> calling makeSetupHook without passing a name is deprecated.
> 'deps' argument to makeSetupHook is deprecated and will be removed in release 23.11., Please use propagatedBuildInputs instead.

fix makeSetupHook deprecations

---

README.md

A couple notes that tripped me up when initially trying this. I hope they can help make future journeys smoother :)
- Getting the syntax of `.sops.yaml` wrong can cause vague errors when it comes to encrypting secrets files.
- `path_regex` needs to include all file extensions that you intend to encrypt. `sops` supports YAML, JSON, ENV, INI and binary files, so suggesting that those be picked up by default seems sensible. Personally, I had trouble figuring out why `sops` wouldn't accept my `.env` file - again with a confusing error message.

Add some helpful tips to the README

---

modules/sops/default.nix

It's supposed to be mdDoc rather than mkDoc.
cc @Mic92

modules/sops: fix description of `useTmpfs`

---

modules/sops/templates/default.nix

currently mixing templates and binary keys in the same configuration b0rks evaluation since `f.read()` speaks utf-8, it also doesn't make sense to template binaries which are not string encoded

don't substitute binaries

---

README.md
pkgs/sops-install-secrets/nixos-test.nix

This follows the rename that was done in nixpkgs.
Reference PR https://github.com/NixOS/nixpkgs/pull/254080

Rename passwordFile to hashedPasswordFile

---

README.md

This line is left over from a set of instructions that were previously incorporated into an early console example under "you can generate yourself a key:" above.

Remove confusing and redundant left over text

---

pkgs/sops-install-secrets/main.go

We import ssh keys by default if openssh is enabled. However if users are using age keys while using sops to deploy ssh keys we have a catch-22.
While users could use lib.mkForce to empty the list, this is not intuitive

allow ssh key import to fail

---

README.md

Since raw passwords don't work, add information about how to create the hashed passwords

Add info about hash passwords

---

modules/sops/templates/default.nix
modules/sops/templates/subs.py

While we can't use non-utf8 data in template, it's not a good idea to use `config.sops.secrets.<name>.format` to determine if a secret is actually utf8 text, as yaml secrets can have embedded binary data (#496) and "binary" secrets can actually contain utf8 text (#439).
With this patch, we only read secret file when the corresponding placeholder actually occurs in template content. This way, we no longer need to try to exclude binary files from the replacement list, but rely on users to only reference text secret in templates.

Only read referenced secret on template rendering

---

modules/sops/default.nix

The assertion below states: "Exactly one of sops.gnupg.home and sops.gnupg.sshKeyPaths must be set".

modules/sops: fix typo

---

README.md

A note was added to the "Setting a user's password" part of the Read-me to help people avoid a serious pitfall. Warns Impermanence Users to link to they keyfile through there persist instead of the normal way.

Update README.md with a note for Impermanence Users

---

modules/sops/default.nix

As of https://github.com/NixOS/nixpkgs/pull/303841/ `lib.mdDoc` is no longer supported.

remove all uses of lib.mdDoc

---

README.md
modules/home-manager/sops.nix

Split out from https://github.com/Mic92/sops-nix/pull/530
```
Apr 16 16:01:22 bsPF1201 systemd[1]: Starting Home Manager environment for sebtm...
Apr 16 16:01:22 bsPF1201 hm-activate-sebtm[1921]: Starting Home Manager activation
Apr 16 16:01:22 bsPF1201 hm-activate-sebtm[1921]: Activating checkFilesChanged
Apr 16 16:01:22 bsPF1201 hm-activate-sebtm[1921]: Activating checkLinkTargets
Apr 16 16:01:22 bsPF1201 hm-activate-sebtm[1921]: Activating writeBoundary
Apr 16 16:01:22 bsPF1201 hm-activate-sebtm[1921]: Activating createGpgHomedir
Apr 16 16:01:22 bsPF1201 hm-activate-sebtm[1921]: Activating migrateGhAccounts
Apr 16 16:01:22 bsPF1201 hm-activate-sebtm[1921]: Activating linkGeneration
Apr 16 16:01:22 bsPF1201 hm-activate-sebtm[1921]: Creating profile generation 1
Apr 16 16:01:22 bsPF1201 …
```

home-manager: Include home.activation-script for linux similar to macos

---

pkgs/sops-install-secrets/darwin.go

On macOS, secretfs sometimes appears on the desktop, which is a bit troublesome for me. Mounting with the `nobrowse` option should avoid this issue.
The other mounting options were derived from already commented code. If there are any issues, please let me know.

sops-install-secrets: add mount options for darwin

---

README.md

- Extraneous redirect removed
- Sops has deprecated the "-o" flag

Minor corrections - README.md

---

modules/home-manager/sops.nix

When even a single unit is failed, `systemd is-system-running` will return `degraded`.  This will prevent sops-nix from being restarted, and will make is seem like sops-nixs under home-manager isn't working.
According to https://www.freedesktop.org/software/systemd/man/latest/systemctl.html#is-system-running, `degraded` means systemd is in a running state (not starting, or stopping), but that there's one or more failed units.
Inspired by https://github.com/nix-community/home-manager/blob/ffe2d07e771580a005e675108212597e5b367d2d/modules/systemd.nix#L358 I've added `degraded` as a state in which the activation script will restart `sops-nix`.
This will help sops-nix under home-manager behave better when there are other, unrelated unit failures on the system.

Allow sops-nix to be restarted when systemd is degraded

---

README.md

`sops -e krb5.keytab` does not encrypt the file, rather it outputs the encrypted data in the console.
`>` should be used here to send the data to the file.

Minor fix for binary example in README.md

---

modules/sops/default.nix
modules/sops/secrets-for-users/default.nix
pkgs/sops-install-secrets/main.go
pkgs/sops-install-secrets/main_test.go
pkgs/sops-install-secrets/nixos-test.nix

https://github.com/Mic92/sops-nix/issues/514
Allow to set uid and gid instead of owner and group. No checks will be performed when uid and gid are set.
```
sops.secrets = {
sslCertificate = {
sopsFile = ./secrets.yaml;
owner = "";
group = "";
uid = config.containers."nginx".config.users.users."nginx".uid;
gid = config.containers."nginx".config.users.groups."nginx".gid;
};
sslCertificateKey = {
sopsFile = ./secrets.yaml;
owner = "";
group = "";
uid = config.containers."nginx".config.users.users."nginx".uid;
gid = config.containers."nginx".config.users.groups."nginx".gid;
};
};
```

Allow to set uid and gid instead of owner and group.

---

modules/home-manager/sops.nix

Add support for configuring environment variables before calling `sops-install-secrets`. Introduce a new `environment` option which allows specifying environment variables. Modify systemd service and launchd agent to use the specified environment variables.

feat(modules/home-manager): add support for configuring environment variables

---

modules/home-manager/sops.nix

The Environment option should be set in Service section.
Fixes #642.

fix(home-manager/sops): fix setting unit env

---

README.md
modules/home-manager/sops.nix
modules/sops/default.nix
pkgs/sops-install-secrets/main.go

Emit plain file when key is empty

---

modules/home-manager/sops.nix

Adding lib to mkOption for defaultSopsKey. 
This should fix https://github.com/Mic92/sops-nix/issues/650

fix missing lib in mkOption

---

modules/sops/templates/default.nix
pkgs/sops-install-secrets/main.go
pkgs/sops-install-secrets/nixos-test.nix

This PR contains 2 commits, I suggest reading them independently:
1. The first commit adds a test that demonstrates <https://github.com/Mic92/sops-nix/issues/652>. It doesn't actually fix the bug.
2. The second commit fixes https://github.com/Mic92/sops-nix/issues/652

Improve activation messages about rendered templates

---

pkgs/sops-install-secrets/main.go
pkgs/sops-install-secrets/nixos-test.nix

This fixes https://github.com/Mic92/sops-nix/issues/653.
Note: `main.go` has been slowly accumulating shared logic between vanilla "secrets" and "templates". It feels to me like we could DRY up some of the logic in here by creating some shared "interface" that they both implement. I opted not to try to tackle that here, though.

fix: create `template.path` symlink

---

modules/sops/templates/default.nix
pkgs/sops-install-secrets/main.go
pkgs/sops-install-secrets/nixos-test.nix

This fixes https://github.com/Mic92/sops-nix/issues/634

Add support for `restartUnits` and `reloadUnits` for templates

---

README.md
modules/home-manager/sops.nix

I'm using Qubes OS and I've configured my Qubes to use [Split GPG](https://www.qubes-os.org/doc/split-gpg). This change adds support for sops-nix to run `/usr/bin/qubes-gpg-client-wrapper` instead of the typical gpg binary. The environment also needs the name of the Qube that has the GPG keys in the environment variable named `QUBES_GPG_DOMAIN`.
I've added myself a todo to consider creating a Nix package for the `/usr/bin/qubes-gpg-client-wrapper` binary available in [this repository](https://github.com/QubesOS/qubes-app-linux-split-gpg). I have not done that right now because I'm new to Qubes OS and I'm not sure what happens if the client version is different than the server running in the vault.

home-manager: Add support for Split GPG on Qubes OS

---

flake.nix
modules/nix-darwin/default.nix
modules/nix-darwin/manifest-for.nix
modules/nix-darwin/secrets-for-users/default.nix
modules/nix-darwin/templates/default.nix
modules/nix-darwin/with-environment.nix
pkgs/sops-install-secrets/darwin.go

Seems like there's other PRs for this already so feel free to discard this one.
I've been trying to get this working locally on my macbook, using this branch of my own config for testing the secrets https://github.com/ianmurphy1/nixcfg/tree/darwin-sops-nix
There was a bug in it where if `config.sops.secrets` was empty then no secrets would be removed as the service would no longer be created due to the service being wrapped in a condition that there needs to be at least one secret to activate. Fixed it on darwin but this bug is present on my nixos too but I didn't touch that part as it's outside the scope of this PR.
The same bug happens with templates too which I still have to figure out so if you're ok with a bug for bug match with darwin then merge away, otherwise I'll keep working on …

Darwin module support

---

modules/home-manager/sops.nix
modules/home-manager/templates.nix

fixes https://github.com/Mic92/sops-nix/issues/665
At least now it evals. Haven't tested templates itself yet.

define templates for home-manager

---

.github/workflows/upgrade-flakes.yml
dev/private.narHash
dev/private/flake.lock
dev/private/flake.nix
flake.lock
flake.nix
modules/nix-darwin/secrets-for-users/default.nix
pkgs/sops-install-secrets/default.nix
shell.nix

Now with home-manager and nix-darwin tests, we don't want to increase
the number of dependencies a user has to override in their flake.lock.

move nixpkgs-stable to private flake inputs

---

pkgs/sops-install-secrets/main.go

NixOS' switch-to-configuration program creates the /run/nixos directory, which may not be present if `system.switch.enable` is `false`.

allow for missing switch-to-configuration directory

---

.mergify.yml
checks/darwin.nix
checks/home-manager.nix
modules/home-manager/sops.nix
modules/home-manager/templates.nix
pkgs/sops-install-secrets/main.go

Fix for #681, or at least trying.
Should probably be squashed, because i kind of bruteforce the issue
EDIT: i did squashed

try fixing templates on home-manager

---

README.md

NB: It's unclear to me why it became unnecessary in that repo.
Any insight?

Fix link to "more complex .sops.yaml example"

---

modules/nix-darwin/default.nix
modules/nix-darwin/secrets-for-users/default.nix

Untested, potentially fixes https://github.com/Mic92/sops-nix/issues/700
please test: @Kidswiss @mettavi

nix-darwin: fix launchd decrypt scripts

---

modules/nix-darwin/secrets-for-users/default.nix

These were enabled even if there wasn't any user secrets.
Also `SOPS_GPG_EXE` is enabled and gpg, etc is added to the system closure as `sops.gnupg.sshKeyPaths` is set by default, should I just set `sops.gnupg.sshKeyPaths = [ ]` downstream?

modules/nix-darwin/secrets-for-users: empty set instead of empty list

---

pkgs/sops-install-secrets/main.go

Fix #708.
1. If `os.Symlink` succeeds (`err == nil`), return `nil` (`err`).
2. If `os.Symlink` fails (`err != nil`), check if the error indicates that a file or directory already exists (`os.IsExist(err)`).
* If the error is unrelated to a pre-existing file or directory, return `err` as it cannot be handled in `atomicSymlink`.
* If the error does indicate a pre-existing file or directory, don't return and handle it with the remaining logic in `atomicSymlink`.
```go
// Fast path: if newname does not exist yet, we can skip the whole dance
// below.
if err := os.Symlink(oldname, newname); err == nil || !os.IsExist(err) {
return err
}
```

Fix fast path in atomicSymlink

---

README.md

I spent too much time trying to understand why secrets were not available at login.
The discussion at https://github.com/Mic92/sops-nix/issues/149 was enlightening and provided the last fix (=make sure that whatever `fileSystems."/where/decryption/keys/are".neededForBoot` is set), so documenting it.

docs: expand a bit on user secrets + impermanence.

---

pkgs/sops-import-keys-hook/sops-import-keys-hook.bash

closes #372
this is an issue for me with `nix-direnv`. i've also tried the suggested solution and it actually does work.

fix import keys hook using unbound variable

---

pkgs/sops-install-secrets/darwin.go
pkgs/sops-install-secrets/linux.go
pkgs/sops-install-secrets/main.go

Currently trying to set ownership of a symlink on MacOS fails with the error: `too many levels of symbolic links`, which is expected behaviour when trying to open a symlink with the flag `O_NOFOLLOW` on MacOS/Darwin; On Linux systems, the `O_NOFOLLOW` can be combined with the `O_PATH` flag, to access a symlink directly but on Darwin systems the combination and the `O_PATH` flag itself doesn't exist; The flag `O_SYMLINK` can be used instead to reference a symlink directly, instead of following it to the target file.
Once the symlink file descriptor reference is successfully obtained, I found that the `Readlinkat` code, as well as the `Fchownat` is also not Darwin-compatible.
In the case of `Readlinkat`, passing a path to a file as the first argument and an empty string as the second is …

Fix symlink ownership change on Darwin systems.

---

modules/sops/default.nix

Fixes #764.
If there is a more sensible fix, I'll happily work on it.

module: set `HOME` envvar to avoid warnings on sops >= 3.10.0

---

modules/home-manager/templates.nix

this feature is not implemented for the home-manager module.
fixes https://github.com/Mic92/sops-nix/issues/729

home-manager/templates: remove restartUnits/reloadUnits

---

modules/sops/secrets-for-users/default.nix

Followup for #765, where I missed this, sorry. :upside_down_face: 
It's needed here too, since it runs in the same context as the default NixOS module.

secrets-for-users: set `HOME` envvar to avoid warnings on sops >= 3.10.0

---

README.md

👋 This PR adds notes on installing and configuring `sops-nix` with [`nix-darwin`](https://github.com/nix-darwin/nix-darwin) for #409!
I found these were the only changes needed when setting things up, with the later steps for setting up `sops` all matching well.

docs: install and configure with nix-darwin

---

default.nix
flake.nix

change to default.nix resolves `nix develop .#unit-tests` error:
```
➜  nix develop .#unit-tests
warning: ignoring untrusted substituter 'https://cache.thalheim.io', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
warning: ignoring the client-specified setting 'trusted-public-keys', because it is a restricted setting and you are not a trusted user
warning: ignoring untrusted substituter 'https://cache.thalheim.io', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
warning: ignoring the client-specified setting 'trusted-public-keys', because it is a restricted setting and you are not a trusted user
++ NIX_PATH=nixpkgs=/nix/store/ninkaf94v6231yv0pyx401zfsw8pkxxx-sourc …
```

Fix checks and tests

---

flake.nix

`homeModules` is the proper name for the output attribute of home-manager modules.
https://github.com/nix-community/home-manager/blob/45c2985644b60ab64de2a2d93a4d132ecb87cf66/flake-module.nix#L23C1-L25C87:
> `homeConfigurations` is for specific installations. If you want to expose
> reusable configurations, add them to `homeModules` in the form of modules, so
> that you can reference them in this or another flake's `homeConfigurations`.
`homeManagerModules` and `homeManagerModule` are kept for backwards compatibility.

use homeModules for the home-manager module output
